SELECT * FROM Swiggy_Data

--DATA VALIDATION AND CLEANING
--NULL CHECKING
SELECT
SUM(CASE WHEN State IS NULL THEN 1 ELSE 0 END)AS null_state,
SUM(CASE WHEN City IS NULL THEN 1 ELSE 0 END)AS null_city,
SUM(CASE WHEN Order_Date IS NULL THEN 1 ELSE 0 END)AS null_order_date,
SUM(CASE WHEN Restaurant_Name IS NULL THEN 1 ELSE 0 END)AS null_restaurant,
SUM(CASE WHEN Location IS NULL THEN 1 ELSE 0 END)AS null_location,
SUM(CASE WHEN Category IS NULL THEN 1 ELSE 0 END)AS null_category,

SUM(CASE WHEN Dish_Name IS NULL THEN 1 ELSE 0 END)AS null_dish,
SUM(CASE WHEN Rating IS NULL THEN 1 ELSE 0 END)AS null_rating,

SUM(CASE WHEN Price_INR IS NULL THEN 1 ELSE 0 END)AS null_price,

SUM(CASE WHEN Rating_Count IS NULL THEN 1 ELSE 0 END)AS null_rating_count
FROM Swiggy_Data1

--BLANK OR EMPTY STRING
SELECT * 
FROM Swiggy_Data 
WHERE
State='' OR City='' OR Restaurant_Name='' OR Location='' OR Category='' OR Dish_Name=''

--DUPLICATE DETECTION
SELECT State,City,Order_Date, Restaurant_name,
Location,Category,Dish_Name,Price_INR, Rating, Rating_Count,
count(*) as CNT 
from Swiggy_Data
GROUP BY
State,City,Order_Date, Restaurant_name,
Location,Category,Dish_Name,Price_INR, Rating, Rating_Count
HAVING count(*)>1


--DELETE DUPLICATION
WITH CTE AS(
SELECT *,ROW_NUMBER() OVER(
	PARTITION BY State,City,Order_Date, Restaurant_name,
Location,Category,Dish_Name,Price_INR, Rating, Rating_Count
ORDER BY (SELECT NULL)
) AS RN 
FROM Swiggy_data
)
DELETE FROM CTE WHERE RN>1


--CREATING SCHEMA
--DIMENSION TABLES
--DATE TABLE
CREATE TABLE DIM_DATE(
	DATE_ID INT IDENTITY (1,1) PRIMARY KEY,
	FULL_DATE DATE,
	YEAR INT,
	MONTH INT,
	MONTH_NAME VARCHAR(20),
	QUARTER INT,
	DAY INT,
	WEEK INT
	)
	--DIM_LOCATION
CREATE TABLE DIM_LOCATION(
	LOCATION_ID INT IDENTITY (1,1) PRIMARY KEY,
	STATE VARCHAR(100),
	CITY VARCHAR(100),
	LOCATION VARCHAR(200)
);

-- DIM RESTAURANT
CREATE TABLE DIM_RESTAURANT(
RESTAURANT_ID INT IDENTITY (1,1) PRIMARY KEY,
RESTAURANT_NAME VARCHAR(200)
);

-- DIM CATEGORY
CREATE TABLE DIM_CATEGORY(
CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY VARCHAR(200)
);

--DIM DISH
CREATE TABLE DIM_DISH (
DISH_ID INT IDENTITY(1,1) PRIMARY KEY,
DISH_NAME VARCHAR(200)
);

SELECT * FROM Swiggy_Data


--FACT TABLE
CREATE TABLE FACT_SWIGGY_ORDERS(
ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
DATE_ID INT,
PRICE_INR DECIMAL(10,2),
RATING DECIMAL(4,2),
RATING_COUNT INT,
LOCATION_ID INT,
RESTAURANT_ID INT,
CATEGORY_ID INT,
DISH_ID INT,
FOREIGN KEY(DATE_ID) REFERENCES DIM_DATE(DATE_ID),
FOREIGN KEY(LOCATION_ID) REFERENCES DIM_LOCATION(LOCATION_ID),
FOREIGN KEY (RESTAURANT_ID) REFERENCES DIM_RESTAURANT(RESTAURANT_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID),
FOREIGN KEY(DISH_ID) REFERENCES DIM_DISH(DISH_ID)
);

SELECT * FROM FACT_SWIGGY_ORDERS


--INSERT DATA IN TABLES
--DIM_DATE
INSERT INTO DIM_DATE(FULL_DATE,YEAR,MONTH,MONTH_NAME,QUARTER,DAY,WEEK)
SELECT DISTINCT
ORDER_DATE,
YEAR(ORDER_DATE),
MONTH(ORDER_DATE),
DATENAME(MONTH,ORDER_DATE),
DATEPART(QUARTER,ORDER_DATE),
DAY(ORDER_DATE),
DATEPART(WEEK,ORDER_DATE)
FROM Swiggy_Data
WHERE ORDER_DATE IS NOT NULL;

SELECT * FROM DIM_DATE

--LOCATION
INSERT INTO DIM_LOCATION(STATE, CITY, LOCATION)
SELECT DISTINCT 
STATE, 
CITY, 
LOCATION
FROM Swiggy_Data;

--restaurant
INSERT INTO DIM_RESTAURANT(RESTAURANT_NAME)
SELECT DISTINCT 
RESTAURANT_NAME
FROM Swiggy_Data;

--category
INSERT INTO DIM_CATEGORY(CATEGORY)
SELECT DISTINCT
CATEGORY 
FROM Swiggy_Data;

--dish
INSERT INTO DIM_DISH(DISH_NAME)
SELECT DISTINCT
DISH_NAME
FROM Swiggy_Data;


--FACT TABLE
INSERT INTO FACT_SWIGGY_ORDERS
(
DATE_ID,
PRICE_INR,
RATING,
RATING_COUNT,
LOCATION_ID,
RESTAURANT_ID,
CATEGORY_ID,
DISH_ID
)
SELECT 
DD.DATE_ID,
S.PRICE_INR,
S.RATING,
S.RATING_COUNT,
DL.LOCATION_ID,
DR.RESTAURANT_ID,
DC.CATEGORY_ID,
DSH.DISH_ID
FROM Swiggy_Data S

JOIN DIM_DATE DD
ON DD.FULL_DATE=S.ORDER_DATE

JOIN DIM_LOCATION DL
ON DL.STATE=S.STATE
AND DL.CITY=S.CITY
AND DL.LOCATION=S.LOCATION

JOIN DIM_RESTAURANT DR
ON DR.RESTAURANT_NAME=S.Restaurant_Name

JOIN  DIM_CATEGORY DC
ON DC.CATEGORY =S.Category

JOIN DIM_DISH DSH
ON DSH.DISH_NAME=S.Dish_Name;


SELECT * FROM FACT_SWIGGY_ORDERS

SELECT * FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID=D.DATE_ID
JOIN DIM_LOCATION L ON F.LOCATION_ID=L.LOCATION_ID
JOIN DIM_RESTAURANT R ON F.RESTAURANT_ID=R.RESTAURANT_ID
JOIN DIM_CATEGORY C ON F.CATEGORY_ID=C.CATEGORY_ID
JOIN DIM_DISH DI ON F.DISH_ID=DI.DISH_ID;


--KPI'S
--TOTAL ORDERS
SELECT COUNT(*) AS TOTAL_ORDERS
FROM FACT_SWIGGY_ORDERS

--TOTAL REVENUE(INR MILLION)
SELECT FORMAT(SUM(CONVERT(FLOAT,PRICE_INR))/100000,'N2')+'INR MILLION' AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS

--AVERAGE DISH PRICE
SELECT FORMAT(AVG(CONVERT(FLOAT,PRICE_INR)),'N2')+'INR' AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS

--AVERAGE RATING
SELECT AVG(RATING) AS AVG_RATING FROM FACT_SWIGGY_ORDERS

--DEEP DRIVE BUSINESS ANALYSIS
--MONTHLY ORDER TRENDS
SELECT D.YEAR,D.MONTH,D.MONTH_NAME,
COUNT(*) AS TOTAL_ORDERS
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID = D.DATE_ID
GROUP BY
D.YEAR,D.MONTH,D.MONTH_NAME
ORDER BY COUNT(*) DESC

--QUATERLY TREND
SELECT D.YEAR,D.QUARTER,
COUNT(*) AS TOTAL_ORDERS
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID = D.DATE_ID
GROUP BY
D.YEAR,D.QUARTER
ORDER BY COUNT(*) DESC

--YEARLY TRENDS
SELECT D.YEAR,
COUNT(*) AS TOTAL_ORDERS
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID = D.DATE_ID
GROUP BY
D.YEAR
ORDER BY COUNT(*) DESC

--ORDERS BY DAY OF WEEK(MON-SUN)
SELECT DATENAME(WEEKDAY, D.FULL_DATE) AS DAY_NAME,
COUNT(*) AS TOTAL_ORDERS
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DATE D ON F.DATE_ID= D.DATE_ID
GROUP BY DATENAME(WEEKDAY,D.FULL_DATE),DATEPART(WEEKDAY,D.FULL_DATE)
ORDER BY DATEPART(WEEKDAY,D.FULL_DATE);

--TOP 10 CITIES BY ORDER VOLUME
SELECT TOP 10
L.CITY,COUNT(*) AS TOTAL_ORDERS FROM FACT_SWIGGY_ORDERS F
JOIN DIM_LOCATION L
ON L.LOCATION_ID=F.LOCATION_ID
GROUP BY L.CITY ORDER BY COUNT(*)DESC

--REVENUE CONTRIBUTION BY STATES
SELECT 
L.STATE,SUM(F.PRICE_INR) AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS F
JOIN DIM_LOCATION L
ON L.LOCATION_ID=F.LOCATION_ID
GROUP BY L.STATE ORDER BY SUM(F.PRICE_INR)DESC

--TOP 10 RESTAURANTS BY ORDERS
SELECT TOP 10 
R.RESTAURANT_NAME,SUM(F.PRICE_INR) AS TOTAL_REVENUE FROM FACT_SWIGGY_ORDERS F
JOIN DIM_RESTAURANT R
ON R.RESTAURANT_ID=F.RESTAURANT_ID
GROUP BY R.RESTAURANT_NAME ORDER BY SUM(F.PRICE_INR)DESC

--TOP CATEGORIES BY ORDER VALUE
SELECT C.CATEGORY,
COUNT(*) AS TOTAL_ORDERDS
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_CATEGORY C ON F.CATEGORY_ID=C.CATEGORY_ID
GROUP BY C.CATEGORY
ORDER BY TOTAL_ORDERDS DESC;

--MOST ORDERED DISH
SELECT D.DISH_NAME, COUNT(*) AS ORDER_COUNT
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_DISH D ON F.DISH_ID = D.DISH_ID
GROUP BY D.DISH_NAME
ORDER BY ORDER_COUNT DESC;

--CUISINE PERFORMANCE (ORDERS+ AVG RATING)
SELECT C.CATEGORY, 
COUNT(*) AS TOTAL_ORDERS,
AVG(CONVERT(FLOAT,F.RATING)) AS AVG_RATING
FROM FACT_SWIGGY_ORDERS F
JOIN DIM_CATEGORY C ON F.CATEGORY_ID=C.CATEGORY_ID
GROUP BY C.CATEGORY
ORDER BY TOTAL_ORDERS DESC;

-- TOTAL ORDERS BY PRICE RANGE
SELECT 
	CASE
			WHEN CONVERT(FLOAT,PRICE_INR)<100 THEN 'UNDER 100'
			WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 100 AND 199 THEN '100-199'
			WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 200 AND 299 THEN '200-299'
			WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 300 AND 499 THEN '300-499'
			ELSE
			'500+'
			END AS PRICE_RANGE,
			COUNT(*) AS TOTAL_ORDERS
		FROM FACT_SWIGGY_ORDERS
		GROUP BY 
			CASE
				WHEN CONVERT (FLOAT,PRICE_INR)<100 THEN 'UNDER 100'
				WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 100 AND 199 THEN '100-199'
				WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 200 AND 299 THEN '200-299'
				WHEN CONVERT (FLOAT,PRICE_INR) BETWEEN 300 AND 499 THEN '300-499'
				ELSE '500+'
			END
		ORDER BY TOTAL_ORDERS DESC;


--RATING COUNT DISTRIBUTION(1-5)
SELECT 
	RATING,
	COUNT(*) AS RATING_COUNT
FROM FACT_SWIGGY_ORDERS
GROUP BY RATING
ORDER BY COUNT(*) DESC;





















